name: "MyBlog"
mode: "dev"
port: 8088
start_time: "2025-11-26"
machine_id: 1

log:
  level: "debug"
  filename : "MyBlog.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "myblogdb"
  max_open_conns: 20
  max_idle_conns: 10
redis:
  host: "127.0.0.1"
  port: 16379
  password: ""
  db: 0
  pool_size: 10

auth:
  jwt_expire: 8760
